name: an_app_v1
description: "An App"
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  firebase_core: ^3.12.1
  firebase_auth: ^5.5.1
  cloud_firestore: ^5.6.5
  flutter_riverpod: ^2.6.1
  shared_preferences: ^2.5.3
  uuid: ^4.5.1
  youtube_player_iframe: ^5.2.1
  webview_flutter: ^4.10.0
  firebase_database: ^11.3.5
  intl: ^0.20.2
  flutter_keyboard_visibility: ^6.0.0
  flutter_native_splash: ^2.4.5 # <- Bağımlılık olarak burada kalması sorun değil (dev_dependencies'de de olabilirdi)
  flutter_launcher_icons: ^0.14.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  riverpod_annotation: ^2.6.1
  build_runner: ^2.4.15
  riverpod_generator: ^2.6.5

flutter_native_splash:
  color: "#faf0e6"
  image: assets/an_splash.png

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/an_logo_1024.png"
  adaptive_icon_background: "#faf0e6"
  adaptive_icon_foreground: "assets/an_adaptive.png"

# --- Flutter Genel Ayarları ---
flutter:
  uses-material-design: true

  # Asset'ler:
  assets:
    - assets/fonts/Quicksand-SemiBold.ttf
    - assets/an_splash.png # <- Splash için kullanılan görsel burada tanımlı, doğru.
    - assets/an_logo.png
    # - images/a_dot_burr.jpeg
    # - images/a_dot_ham.jpeg

  # Fontlar:
  fonts:
    - family: Quicksand
      fonts:
        - asset: assets/fonts/Quicksand-SemiBold.ttf
          weight: 600
    # - family: Schyler
    #   fonts:
    #     - asset: fonts/Schyler-Regular.ttf
    #     - asset: fonts/Schyler-Italic.ttf
    #       style: italic
    # - family: Trajan Pro
    #   fonts:
    #     - asset: fonts/TrajanPro.ttf
    #     - asset: fonts/TrajanPro_Bold.ttf
    #       weight: 700